### PR TITLE
Style enhancement: Use sidebar collapse plugin to manage `_sidebar.md`

### PR DESCRIPTION
**Pull request by Tr0py**
This patch is trying to solve the issue https://github.com/Emanual20/Emanual20.github.io/issues/214

Problem: maintaining multiple `_sidebar.md` for each folder costs time.

Solution: use [docsify-sidebar-collapse](https://github.com/iPeng6/docsify-sidebar-collapse)
to automatically manage sidebar, with only one `_sidebar.md`.

What is done in this commit:
1. Merged all `_sidebar.md`s to one `_sidebar.md` at root folder.
2. Enable plugin in `index.html`.
3. Fixed a bug: there was  no `大四课程` in `_sidebar.md` previously.  Added.

### CODE REVIEW

**Comment by Tr0py** [comment]
一句话总结：使用插件([docsify-sidebar-collapse](https://github.com/iPeng6/docsify-sidebar-collapse))管理`_sidebar.md`, 从而可以只需要维护一个`_sidebar.md`即可实现左侧导航栏的展开/收缩功能。

以后对于目录的修改只需要修改根目录下的`_sidebar.md`即可，不必重复进入每一层目录进行修改。

**Comment by Tr0py** [comment]
demo体验：https://tr0py.github.io/NKUICS/#/

**Comment by Tr0py** [comment]
测试视频：
Kapture 2022-07-08 at 00 33 45

**Comment by Emanual20** [comment]
Dear Tr0py, 

Thanks for your attention to NKUCS.ICU.

This problem you mentioned was left by the framework we refer to which was first written by the IEEE class of SJTU. It was obviously a huge obstacle for previously maintenance and devotion by others.

That solution you mentioned is tremendously elegant. We express our sincere appreciation for your attention and devotion to NKUCS.ICU. We have merged that pull request. Looking forward to more participation and cooperation in the development of NKUCS.ICU community.

Best Wishes, 
Emanual20

**Pull request merged**
